project:
  type: book

book:
  title: "TITLE"
  author: "AUTHOR"
  date: today
  site-url: https://[ACCOUNT NAME].github.io/[REPO NAME]
  repo-url: https://github.com/[ACCOUNT NAME]/[REPO NAME]
  repo-branch: main
  repo-actions: [source, edit, issue]
  chapters:
    - index.qmd
    - timeseries.qmd
    - chapter1.qmd
    - chapter2.qmd
    - chapter3.qmd

format:
  html:
    theme: [default, style/graphs.scss]
    code-link: true
    highlight-style: style/joyce.theme
    callout-icon: false
    fig-width: 5
    fig-height: 4
    
knitr:
  opts_chunk: 
    fig.align: center
    out.width: 60%
    
    
execute:
  echo: true
  warning: false
  message: false
  error: true
  cache: true

editor: source

